### ISSUE TITLE
Bring luvi (and luvit environments) to Lua 5.3

### ISSUE THREAD

**Issue by starwing** [luvit/luvi#140]
Hi dear @creationix,

I have done to port luvi into Lua 5.3, some modifies to:
  - lrexlib: compatible with Lua 5.3
  - lua_zlib: compatible with Lua 5.3
  - luv:
      - add lua_add_executable() to lua.cmake.
      - remove `LUA_USE_DLOPEN` when Win32.
  - add `env.os` and `env.arch` to lenv.c
  - add global `unpack` and `loadstring` to lvuibundle.lua
  - add Lua 5.3 compatible to luvi.h
  - add a compatible `bit` module to fit `lit`.

After that, lit now works with Lua 5.3 now. but luvit still doesn't work. I hope lit package manager can add depends like "lua > 5.1" or "luajit > 2.0" to enable modules for luajit or lua. So we can write plain Lua script in lit (but not luvit itself).

as there are many modifies, so I hope a guide how to make a pull request :(

regards,
Xavier Wang.

**Comment by creationix** [comment]
So my long-term goal is similar.  I'm trying to move to a future where the current "luvit" binary is never needed in normal development.  I like using lit for package management and I like luvi for cases where I want to make a single binary.  It's neat that you got lit working in lua 5.3.

I don't use lrexlib or lua_zlib in luvit or lit.  I know of at least one company using lua_zlib in their own custom luvi-based project and I have future plans to do a work-related project that will need lrexlib.

I would like to strip luvi down to the bare essentials to allow it to bundle libuv, miniz (for zip reading) and a lua engine of choice.  The hard part is what to do for people who want optional addons like zlib and openssl.  Perhaps I'll have to stop trying to make pre-built binaries for all platforms for all possible options?

The lua code in luvi has been moving out to pure-lua modules.  Last week, for example, I published `creationix/pathjoin` which is the path code in luvi. https://luvit.io/lit.html#author:creationix%20name:pathjoin

Since I want the common case to be people using lit only for package management and not using the luvit runtime at all (except as a set of dependencies), it makes sense to first send your 5.3 patches to lrexlib and lua_zlib upstream to the main projects.  I've already been building servers using plain luajit + luv installed via luarocks with lit packages like weblit installed locally in the project tree.  I plan on writing a blog post on this soon.

**Comment by starwing** [comment]
Thanks for reply :)

I have made push request to lrexlib, but they prefer LUA_COMPAT_5_2, we still discuss about that.

I removed lua_zlib's patch, as luvi used a old version of lua_zlib, and new version already have Lua 5.3 compatible.

the luv patch is merged, but it need luvi modifies to use `lua_add_execute()` instead of `luajit_add_executable()`. and modifies to main.c (include Lua files in `vm_acquire()`).

I will make the pull request fast, because `luv` already merged my request, if not proper modifes to luvi, it can not pass build even in luajit mode (as the name changed of `luajit_add_executable()`)

Regards.

**Comment by starwing** [comment]
for the path support, I have a pure C path module [lpath](https://github.com/starwing/lpath), maybe it worth to look, it support Python style path routines into Lua (but switched to lua flavor)

**Comment by starwing** [comment]
@creationix maybe we should release standard minialize luvi for each support plaform, and binary packages for non-essentials modules?

I mean, make lit support binary repo, download right binary modules againest current platform. as now the lit make download luvi.exe, we download zlib.dll, openssl.dll, lrexlib.dll, etc. all modules can upload by volunteer or auto-build. all linked againest luvi.exe, just like node.exe.

**Comment by creationix** [comment]
I've explored the area of luvi apps pulling in dynamic libraries.  It's supported as much as possible, but there are problems since the dll needs to be embedded in the zip-file where dlopen can't access it.

There is logic in the `luvit/require` module to extract the library to a temporary folder and dlopen it from there.  lit has logic to allow packages to publish prebuilt binaries for many platforms, but only include the matching platform when building a package.

But for the virgo agent (the biggest user of luvi I know of), this doesn't work because the agent needs to run on machines that have noexec set for their temporary directories.  Also the agent doesn't always have a clear place it can extract the temporary files to disk.  For these reasons, the agent needs to have a luvi fork with all it's binary modules included at compile time (including some not in the main repo).

I haven't even tried to address the problem of building modules on demand since it's such a hard problem and impossible on the machines I want to target as users of lit (namely machines without C compilers at all.)  I'm fine with eventually having something like npm's system, but it's low priority compared to other issues because the high cost and relatively low gain.
