### ISSUE TITLE
Outdated usage of luvi

### ISSUE THREAD

**Issue by joerg-krause** [luvit/luvi#157]
The luvi README and usage help text both say:

```
  # Run an app that layers on top of luvit
  luvi path/to/app path/to/luvit
```

This seems to be an outdated usage of luvi: https://github.com/luvit/luvit/issues/948

**Comment by creationix** [comment]
I'm pretty sure the layered approach still works in luvi itself https://github.com/luvit/luvi/blob/master/src/lua/luvibundle.lua#L204-L221

It looks like we even still have auto-register for luvit's require system. https://github.com/luvit/luvi/blob/master/src/lua/luvibundle.lua#L327-L338

As I mentioned in the other issue, I believe your issue is you're not calling luvit's bootstrap function that sets up the global environment.  If you layer luvit underneath your app, then you probably can't see luvit's `init.lua` anymore.  It's not at `deps/luvit/init.lua` in any case.  You need to call the bootstrap function to get the same globalas as are present in luvit.  

https://github.com/luvit/luvit/blob/master/examples/custom-binary/main.lua#L3-L9
```lua
return require('luvit')(function (...)
  print("Custom main with custom builtins!")
  print("1 + 2", require("add")(1, 2))
  print("3 - 2", require("multi")(3, 2))
  p(process.argv)
  p(...)
end, ...)
111

**Comment by joerg-krause** [comment]
Long time. I've checked and the layered approach does work.

Minimal example, _app/main.lua:_
``` lua
p("hello world")
```

Running `luvi app path/to/luvit`:
```
'hello world'
```
