### ISSUE TITLE
feature request, how about lua buffer

### ISSUE THREAD

**Issue by zhaozg** [luvit/luvi#74]
When lua handle network I/O, we need a fast buffer, please consider the possibility of lbuffer in luvi.
A mutable string support to lua, https://github.com/starwing/lbuffer

**Comment by imzyxwvu** [comment]
Since Lua strings need hash calculating when they are being created and immutable, creating them is slower. But they are very fast when being compared and indexed with. Actually Lua strings are fast enough. I created an TCP/IP stack mostly in Lua and it heavily depends on Lua strings, but it could generate more than 3000 IP frames per second on my RPi2.

The problems I guess we would meet:

1. When Lua strings are used as table indexes, they are used as values, but userdatas would be used as references. This might make old Lua users feel confused. They have to be aware to convert buffers into Lua strings.

2. Decoder-style stream demuxers heavily depend on Lua string pattern match APIs for line-text protocols. They would not benefit from this kind of buffers. If a raw find method is implemented, this problem would disappear.

3. luajit could inline some string operations. If buffers are implemented in a foreign library, this optimize could not take place.

**Comment by creationix** [comment]
Is speed really a bottleneck using strings in a real use case?  I also made a test http server that decodes the http protocol using lua string methods and it was able to handle insanely high speeds on my desktop computer.

**Comment by zhaozg** [comment]
Yes, I think lua string enough to handle plain text protocol,include HTTP,SMTP,POP.
But please think about to inline handle msgpack or SNMP binary based protocol.
Maybe string.pack and string.unpack come from lua5.3 will better solution. I prefer to string.pack/unpack than mutable string.

**Comment by imzyxwvu** [comment]
string.pack and string.unpack could be found in a C library called struct. There is also one msgpack implement for Lua you could found in msgpack homepage.

**Comment by zhaozg** [comment]
Combine string pack/unpack in luvi better than extern module.

**Comment by zhaozg** [comment]
Close this, https://github.com/luvit/luvi/pull/76
